slackToken: ""
replicaCount: 1
image:
  repository: gcr.io/ic-cloud/nannybot
  tag: e5c2beb66dea79c7cf111a5c9bb300c16e779a9a
  pullPolicy: Always
nameOverride: ""
fullnameOverride: ""
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: false
  annotations: {}
  path: /
  hosts:
  - chart-example.local
  tls: []
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
