slackToken: ""
replicaCount: 1
image:
  repository: gcr.io/ic-cloud/nannybot
  tag: 999a0bc361edf03c32acfe50402049ee21ce5f78
  pullPolicy: Always
nameOverride: ""
fullnameOverride: ""
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: false
  annotations: {}
  path: /
  hosts:
  - chart-example.local
  tls: []
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
